name: Run tests

on:
  pull_request:
  schedule:
    - cron: "53 0 * * *" # Daily at 00:53 UTC
  workflow_dispatch:
  workflow_call:

jobs:
  tox-lint:
    name: tox run -e lint
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install tox & poetry
        run: |
          pipx install tox poetry
      - name: Set up python environment
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "poetry"
      - name: Run linters
        run: tox run -e lint

  unit-test:
    name: Unit test charm
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Install tox & poetry
        run: |
          pipx install tox poetry
      - name: Set up python environment
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "poetry"
      - name: Run tests
        run: tox run -e unit
